env:
  browser: true
  es2021: true
extends: [plugin:prettier/recommended, airbnb-base]
plugins: [prettier]
rules: {
  prettier/prettier: "error",
  "import/prefer-default-export": [
    ( "off" | "warn" | "error" ),
    # default is "single"
    { "target": ("single" | "any") }
  ],
}
parserOptions:
  ecmaVersion: latest
  sourceType: module
